Task/update cli arguments
jamatute/locustor pull request #1
Opened 2018-11-08 15:22 UTC by rbenvos

2018-11-12 10:21 UTC, jamatute commented on locustor/cli_arguments.py
> +# import os
Si no es necesario borra los comentarios plz

2018-11-12 10:21 UTC, jamatute commented on locustor/cli_arguments.py
> +# import yaml
Si no es necesario borra los comentarios plz

2018-11-12 10:21 UTC, jamatute commented on locustor/locustor.py
> +        time.sleep(30)
Este sleep era necesario?

2018-11-12 10:21 UTC, jamatute commented on locustor/locustor.py
> +            # with open(csv_file, 'r') as f:
Si ya no es necesario lo borraría

2018-11-12 10:21 UTC, jamatute commented on tests/test_locustor.py
> +# class TestLocustorLoad(TestLocustor):
Por qué me quitas tests gratuitamente maldito!

2018-11-13 10:37 UTC, rbenvos commented on tests/test_locustor.py
> +# class TestLocustorLoad(TestLocustor):
No aplican

2018-11-13 10:41 UTC, rbenvos commented on locustor/locustor.py
> +        time.sleep(30)
el paquete de locust no cierra manualmente el fichero de escritura, lo cual tenemos que dejar una ventana de tiempo para que se cierre manualmente

2018-11-13 16:09 UTC, jamatute reviewed
Muchas gracias por la PR!! 

Si ves que soy quisquilloso en los comentarios no lo tomes muy a pecho, que muchas cosas son opiniones.

En general me parece un currazo :)

P.D: Eres la primera PR que me hacen a un repo de github \o/

2018-11-13 16:09 UTC, jamatute commented on locustor/cli_arguments.py
> +# import os
Borrame los comentarios plz!

2018-11-13 16:09 UTC, jamatute commented on locustor/cli_arguments.py
> +# import yaml
Borrame los comentarios plz!

2018-11-13 16:09 UTC, jamatute commented on locustor/locustor.py
> +        time.sleep(30)
Creo recordar que te lo pregunté, pero para que era el sleep?

2018-11-13 16:09 UTC, jamatute commented on locustor/locustor.py
> +        file = open('{work_dir}/{inform_name}_result.json'.format(work_dir=self.work_dir, inform_name=self.inform_name),
Estoy de acuerdo en no corregir el pep8 de todo el documento, pero al menos que lo que metamos lo cumpla

2018-11-13 16:09 UTC, jamatute commented on locustor/locustor.py
> +        return inform
Esto ya es estilo mio, pero usaria `informe` en vez de inform, pierdes una letra pero creo que queda más claro y reproducible

2018-11-13 16:09 UTC, jamatute commented on locustor/locustor.py
> +        return inform.get('fail_ratio') < self.fail_ratio or False
No sobra el `or False`? si no es True, es False xD

2018-11-13 16:09 UTC, jamatute commented on tests/test_locustor.py
> +test_locustfile = os.path.dirname(os.path.abspath(__file__))+'/test_data/locustfile.py'
por PEP8 agregar un espacio entre ` + `

2018-11-13 16:09 UTC, jamatute commented on tests/test_locustor.py
> +        self.tmp_dir = tempfile.NamedTemporaryFile().name
Qué ventaja de ta respecto a mkdtemp?

2018-11-13 16:09 UTC, jamatute commented on tests/test_locustor.py
> +        self.assertIn('locustor/locustor/generic_locustfile.py', self.locustor.locust_file)
No deberia de ser assertEqual?

2018-11-13 16:09 UTC, jamatute commented on tests/test_locustor.py
> +    def test_locustor_run_method_ok(self):
Quizá le pondría un nombre más claro al test

2018-11-13 16:09 UTC, jamatute commented on tests/test_locustor.py
> +        self.assertFalse(self.locustor.get_result())
Aquí estás haciendo el test de dos cosas en el mismo test, no sería mejor separarlo en dos tests?

2018-11-14 07:29 UTC, rbenvos commented on locustor/locustor.py
> +        time.sleep(30)
En el paquete oficial de locust no 'cierran' el fichero lo cual hasta que se hace de manera automática hay que darle una ventana.

2018-11-14 07:30 UTC, rbenvos commented on locustor/locustor.py
> +        file = open('{work_dir}/{inform_name}_result.json'.format(work_dir=self.work_dir, inform_name=self.inform_name),
ña ña ña

2018-11-14 07:32 UTC, rbenvos commented on tests/test_locustor.py
> +        self.tmp_dir = tempfile.NamedTemporaryFile().name
Principalmente por que mkdtemp generaba un fichero que no tenia visibilidad, y daba problemas e investigando un poco planteaban que era mejor para test usando esta clase

2018-11-14 07:33 UTC, rbenvos commented on tests/test_locustor.py
> +        self.assertIn('locustor/locustor/generic_locustfile.py', self.locustor.locust_file)
Es para que sea agnostico de la ruta del fichero es asi aposta

2018-11-14 07:35 UTC, rbenvos commented on locustor/locustor.py
> +        file = open('{work_dir}/{inform_name}_result.json'.format(work_dir=self.work_dir, inform_name=self.inform_name),
done!

2018-11-14 08:27 UTC, jamatute commented on examples/example1.py
> +print('Pasa el test:{}'.format(locustor.get_result()))
Cohona, ponlo en ingles

2018-11-14 08:27 UTC, jamatute commented on locustor/locustor.py
> +        file = open('{work_dir}/{inform_name}_result.json'.format(work_dir=self.work_dir, inform_name=self.inform_name),
ña ña ña,  sigue teniendo más de 80 caracteres, pero como ya te he tocado mucho la moral lo cierro

2018-11-14 08:28 UTC, jamatute commented on locustor/locustor.py
> +        return inform.get('fail_ratio') < self.fail_ratio or False
Te falta este!

2018-11-14 08:30 UTC, jamatute requested changes

2018-11-14 08:30 UTC, jamatute commented on tests/test_cli_arguments.py
> +    @unittest.skip("reason for skipping")
Plz, pon la razon del skip

2018-11-14 08:37 UTC, rbenvos commented on tests/test_cli_arguments.py
> +    @unittest.skip("reason for skipping")
done

2018-11-14 08:38 UTC, rbenvos commented on locustor/locustor.py
> +        return inform.get('fail_ratio') < self.fail_ratio or False
con el or False te asegurar que devuelve un false y tuviese un valor nulo el elemento
 `a = {'a': None}
a.get('a') or False
print(a.get('a'))
None
print(a.get('a')or False)
False`

2018-11-14 12:11 UTC, rbenvos commented on tests/test_cli_arguments.py
> +    @unittest.skip("reason for skipping")
commit ab8983eb78ae0a83637b7be08711424f168fcf39

2018-11-14 12:11 UTC, rbenvos commented on examples/example1.py
> +print('Pasa el test:{}'.format(locustor.get_result()))
commit ca83540e3c351e772cb37a98c999e320b2251073

2018-11-14 14:19 UTC, jamatute approved these changes

2018-11-14 14:19 UTC, merged